import type { Metadata } from 'next';
import { Jua } from 'next/font/google';
import './globals.css';

const jua = Jua({
	subsets: ['latin'],
	weight: '400'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>): JSX.Element {
	return (
		<html lang="en">
			<body className={jua.className}>{children}</body>
		</html>
	);
}
