import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from '@/redux/provider';
import { ThemeProvider } from '@/components/providers/themeProvider';

import { Toaster } from '@/components/ui/sonner';

const inter = Inter({
	subsets: ['latin'],
	weight: '400'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>): JSX.Element {
	return (
		<html lang="en">
			<ReduxProvider>
				<body className={inter.className}>
					<ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
						{children}
					</ThemeProvider>
					<Toaster />
				</body>
			</ReduxProvider>
		</html>
	);
}
